ALTER TABLE "admin_audit_logs"
  DROP CONSTRAINT "admin_audit_logs_action_check",
  ADD CONSTRAINT "admin_audit_logs_action_check" CHECK ("action" IN (
    'CATEGORY_CREATE', 'CATEGORY_UPDATE', 'CATEGORY_ARCHIVE',
    'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_PUBLISH', 'PRODUCT_ARCHIVE',
    'PRODUCT_MEDIA_SIGNATURE', 'PRODUCT_MEDIA_REGISTER', 'PRODUCT_MEDIA_UPDATE', 'PRODUCT_MEDIA_REMOVE',
    'PRICE_CREATE', 'INVENTORY_ADJUST',
    'PROMOTION_CREATE', 'PROMOTION_UPDATE', 'PROMOTION_PUBLISH', 'PROMOTION_ARCHIVE',
    'PROMOTION_MEDIA_SIGNATURE', 'PROMOTION_MEDIA_REGISTER', 'PROMOTION_MEDIA_REMOVE',
    'ORDER_STATUS_TRANSITION'
  ));

ALTER TABLE "admin_audit_logs"
  DROP CONSTRAINT "admin_audit_logs_entity_type_check",
  ADD CONSTRAINT "admin_audit_logs_entity_type_check" CHECK ("entity_type" IN (
    'CATEGORY', 'PRODUCT', 'PRODUCT_MEDIA', 'PRICE', 'INVENTORY',
    'PROMOTION', 'PROMOTION_MEDIA', 'ORDER'
  ));
